name: appforge_cli
license: MIT
description: A powerful CLI to generate production-ready Flutter apps with Firebase, localization, Docker, and modular architecture.
version: 0.1.3
homepage: https://github.com/appforge-cli/appforge_cli/
repository: https://github.com/appforge-cli/appforge_cli/
issue_tracker: https://github.com/appforge-cli/appforge_cli/issues/

environment:
  sdk: '>=3.0.0 <4.0.0'

topics:
  - cli
  - flutter
  - generator
  - firebase
  - scaffold

documentation: https://github.com/appforge-cli/appforge_cli#readme

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  recase: ^4.1.0
  yaml: ^3.1.2
  interact: ^2.2.0
  mason_logger: ^0.3.3
  watcher: ^1.2.0
  meta: ^1.17.0
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.0

executables:
  appforge: appforge_cli
