name: superapp_cli
description: A powerful CLI to generate production-ready Flutter apps with Firebase, localization, Docker, and modular architecture.
version: 0.1.0
homepage: https://github.com/ajaychikshetty/superapp_cli
repository: https://github.com/ajaychikshetty/superapp_cli
issues_tracker: https://github.com/ajaychikshetty/superapp_cli/issues/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  recase: ^4.1.0
  yaml: ^3.1.2
  interact: ^2.2.0
  mason_logger: ^0.2.11
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.0

executables:
  superapp: superapp
